# app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: appserver
  labels:
    name: appserver
spec:
  type: LoadBalancer
  ports:
    - port: 443
      name: appserver-https
      targetPort: 443
      protocol: TCP
  selector:
    name: appserver
